categories:
  WaveMailer:
    label: 'Wave Mailer'
  WaveMailer.pages:
    label: 'Pages'
    parent: WaveMailer
  WaveMailer.fields:
    label: 'Configure shown fields and required fields'
    parent: WaveMailer

settings:
  waveMailer.includeCSS:
    label: 'Include CSS'
    type: bool
    category: WaveMailer
    description: 'Include the default CSS of wave-mailer'
    default: true

  waveMailer.confirmationPage:
    label: 'Confirmation page'
    type: page
    category: WaveMailer.pages
    description: 'Page to redirect after a successful registration'
    default: 0

  waveMailer.manageSubscriptionPage:
    label: 'Manage Subscription page'
    type: page
    category: WaveMailer.pages
    description: 'Page to manage the subscriptions'
    default: 0

  waveMailer.doubleOptInPage:
    label: 'DoubleOptIn page'
    type: page
    category: WaveMailer.pages
    description: 'Page with the double opt-in form'
    default: 0

  waveMailer.storagePid:
    label: 'Storage page'
    type: page
    category: WaveMailer.pages
    description: 'Page to store new subscribers'
    default: 0

  waveMailer.fromAddress:
    label: 'From E-Mail Address'
    type: text
    category: WaveMailer
    description: 'The E-Mail address to send the mails from'
    default: 'noreply@example.org'

  waveMailer.senderName:
    label: 'Sender name'
    type: text
    category: WaveMailer
    description: 'The name to send the mails from'
    default: 'example.org'

  waveMailer.showFirstName:
    label: 'Show first name field in the form'
    type: bool
    category: WaveMailer.fields
    default: true

  waveMailer.requireFirstName:
    label: 'Require first name field in the form'
    type: bool
    category: WaveMailer.fields
    default: false

  waveMailer.showLastName:
    label: 'Show last name field in the form'
    type: bool
    category: WaveMailer.fields
    default: true

  waveMailer.requireLastName:
    label: 'Require last name field in the form'
    type: bool
    category: WaveMailer.fields
    default: false

  waveMailer.showSalutation:
    label: 'Show salutation field in the form'
    type: bool
    category: WaveMailer.fields
    default: true




