base: https://surfcamp-team-wavemailer.ddev.site/
dependencies:
  - typo3/theme-camino
  - beffp/wave-mailer
languages:
  -
    title: English
    enabled: '1'
    locale: en-US
    hreflang: en-US
    base: /
    websiteTitle: Camino
    navigationTitle: English
    flag: global
    languageId: 0
rootPageId: 1
websiteTitle: Camino
